services:
  shop404:
    image: ghcr.io/puttrix/shop404:latest
    ports:
      - "${PUBLISH_PORT:-8080}:3000"
    environment:
      - PORT=${PORT:-3000}
      - GTM_ID=${GTM_ID:-}
      - GA4_ID=${GA4_ID:-}
      - GTM_SERVER_CONTAINER_URL=${GTM_SERVER_CONTAINER_URL:-}
      - MATOMO_TAG_MANAGER_CONTAINER_URL=${MATOMO_TAG_MANAGER_CONTAINER_URL:-}
      - OPTIMIZELY_WEB_SNIPPET_URL=${OPTIMIZELY_WEB_SNIPPET_URL:-}
      - ODP_SDK_URL=${ODP_SDK_URL:-}
